FROM python:3.14-slim

WORKDIR /app

RUN apt-get update \
    && apt-get install -y --no-install-recommends stockfish \
    && rm -rf /var/lib/apt/lists/*

# copy requirements from llm folder
COPY llm/requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt

# copy only llm code
COPY llm /app/llm
RUN mkdir -p /app/data

ENV PYTHONPATH=/app

CMD ["uvicorn", "llm.server:app", "--host", "0.0.0.0", "--port", "8000"]
